### ISSUE TITLE
error occurred when marking research as done

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#13]
````
[ERR 01Nov2020  20:51:54.662] Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Unsupported Operation
	at org.qommons.collect.BetterList$ConstantList$2.set(BetterList.java:1486)
	at org.observe.collect.ObservableCollectionImpl$FlattenedValueCollection$MutableFlattenedValueElement.set(ObservableCollectionImpl.java:3817)
	at org.quark.ogame.uni.ui.PlanetTable.lambda$125(PlanetTable.java:514)
	at org.observe.util.swing.CategoryRenderStrategy$CategoryMutationStrategy.lambda$0(CategoryRenderStrategy.java:48)
	at org.observe.util.swing.CategoryRenderStrategy$CategoryMutationStrategy.mutate(CategoryRenderStrategy.java:181)
	at org.observe.util.swing.ObservableTableModel.setValueAt(ObservableTableModel.java:229)
	at javax.swing.JTable.setValueAt(Unknown Source)
	at javax.swing.JTable.editingStopped(Unknown Source)
	at org.observe.util.swing.ObservableCellEditor$DefaultObservableCellEditor.stopCellEditing(ObservableCellEditor.java:405)
	at org.observe.util.swing.ObservableCellEditor.lambda$5(ObservableCellEditor.java:186)
	at org.observe.Observable$2.onNext(Observable.java:58)
	at org.observe.SimpleObservable.lambda$2(SimpleObservable.java:228)
	at org.qommons.collect.ListenerList.forEach(ListenerList.java:452)
	at org.observe.SimpleObservable.onNext(SimpleObservable.java:227)
	at org.observe.SimpleSettableValue.set(SimpleSettableValue.java:137)
	at org.observe.SettableValue$2.set(SettableValue.java:159)
	at org.observe.util.swing.ObservableComboBoxModel.lambda$8(ObservableComboBoxModel.java:254)
	at org.observe.util.swing.ObservableComboBoxModel.lambda$11(ObservableComboBoxModel.java:155)
	at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
	at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
````

**Comment by Updownquark** [comment]
Fixed it.  :-)
