### ISSUE TITLE
Error Dragging New Planet

### ISSUE THREAD

**Issue by Updownquark** [Updownquark/OGame-ROI#14]
I created a new planet on my account, renamed it, then dragged it to up 1 position.

```
[ERR 18Nov2020  09:51:35.802] java.lang.UnsupportedOperationException: No setter found for field org.quark.ogame.uni.Planet.account
	at org.observe.util.EntityReflector$ReflectedField.set(EntityReflector.java:464)
	at org.observe.config.EntityConfiguredValueType$EntityConfiguredValueField.set(EntityConfiguredValueType.java:193)
	at org.observe.config.ObservableConfigFormat$EntityConfigFormatImpl$EntityFieldSetter.set(ObservableConfigFormat.java:1193)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parseUpdatedField(ObservableConfigFormat.java:1086)
	at org.observe.config.ObservableConfigFormat$EntityConfigFormatImpl.parseUpdatedField(ObservableConfigFormat.java:1472)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parse(ObservableConfigFormat.java:887)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection$ConfigElement.<init>(ObservableConfigTransform.java:577)
	at org.observe.config.ObservableConfigTransform$ObservableConfigEntityValues$ConfigValueElement.<init>(ObservableConfigTransform.java:1037)
[ERR  09:51:35.804] 	at org.observe.config.ObservableConfigTransform$ObservableConfigEntityValues.createElement(ObservableConfigTransform.java:1019)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection.onChange(ObservableConfigTransform.java:421)
	at org.observe.config.ObservableConfigFormat$2.parse(ObservableConfigFormat.java:1569)
	at org.observe.config.ObservableConfigFormat$2.parse(ObservableConfigFormat.java:1)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parseUpdatedField(ObservableConfigFormat.java:1072)
	at org.observe.config.ObservableConfigFormat$EntityConfigFormatImpl.parseUpdatedField(ObservableConfigFormat.java:1472)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parse(ObservableConfigFormat.java:906)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection.onChange(ObservableConfigTransform.java:443)
	at org.observe.Observable$2.onNext(Observable.java:58)
	at org.observe.config.ObservableConfig.lambda$9(ObservableConfig.java:1174)
	at org.qommons.collect.ListenerList.forEach(ListenerList.java:452)
[ERR  09:51:35.805] 	at org.observe.config.ObservableConfig._fire(ObservableConfig.java:1169)
	at org.observe.config.ObservableConfig.fire(ObservableConfig.java:1160)
	at org.observe.config.ObservableConfig._fire(ObservableConfig.java:1187)
	at org.observe.config.ObservableConfig.fire(ObservableConfig.java:1160)
	at org.observe.config.ObservableConfig._fire(ObservableConfig.java:1187)
	at org.observe.config.ObservableConfig.fire(ObservableConfig.java:1160)
	at org.observe.config.ObservableConfig.addChild(ObservableConfig.java:1020)
	at org.observe.config.ObservableConfig.addChild(ObservableConfig.java:1009)
	at org.observe.config.ObservableConfig.moveChild(ObservableConfig.java:1034)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection$OCBCCollection.move(ObservableConfigTransform.java:819)
	at org.observe.collect.ObservableCollectionImpl$PassiveDerivedCollection.move(ObservableCollectionImpl.java:2265)
	at org.observe.collect.ObservableCollectionImpl$FlattenedValueCollection.move(ObservableCollectionImpl.java:3371)
	at org.observe.collect.ObservableCollectionActiveManagers$BaseCollectionManager.move(ObservableCollectionActiveManagers.java:522)
	at org.observe.collect.ObservableCollectionActiveManagers2$ActiveRefreshingCollectionManager.move(ObservableCollectionActiveManagers2.java:731)
	at org.observe.collect.ObservableCollectionActiveManagers$ActiveTransformedCollectionManager.move(ObservableCollectionActiveManagers.java:1455)
	at org.observe.collect.ObservableCollectionImpl$ActiveDerivedCollection.move(ObservableCollectionImpl.java:3054)
	at org.observe.collect.ObservableCollectionImpl$PassiveDerivedCollection.move(ObservableCollectionImpl.java:2265)
	at org.observe.collect.ObservableCollectionActiveManagers$BaseCollectionManager.move(ObservableCollectionActiveManagers.java:522)
	at org.observe.collect.ObservableCollectionActiveManagers2$FlattenedManager.move(ObservableCollectionActiveManagers2.java:1532)
	at org.observe.collect.ObservableCollectionImpl$ActiveDerivedCollection.move(ObservableCollectionImpl.java:3054)
	at org.observe.util.SafeObservableCollection.move(SafeObservableCollection.java:287)
	at org.observe.util.swing.SimpleTableBuilder$TableBuilderTransferHandler.importData(SimpleTableBuilder.java:1015)
	at java.desktop/javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1544)
	at java.desktop/java.awt.dnd.DropTarget.drop(DropTarget.java:452)
	at java.desktop/javax.swing.TransferHandler$SwingDropTarget.drop(TransferHandler.java:1282)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(SunDropTargetContextPeer.java:547)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(SunDropTargetContextPeer.java:863)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:787)
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4855)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[ERR  09:51:35.808] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4622)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[ERR  09:51:35.809] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Updownquark** [comment]
Fixed this
